class CfgPatches
{
	class MET_Deathwatch_Units
	{
		units[]=
		{
			"MET_mandalorian_deathwatchWarrior",
			"MET_mandalorian_deathwatchHeavy",
			"MET_mandalorian_deathwatchRTO",
			"MET_mandalorian_deathwatchMedic",
			"MET_mandalorian_deathwatchMarksman",
			"MET_mandalorian_deathwatchAT",
			"MET_mandalorian_deathwatchHeavyAA",
			"MET_mandalorian_deathwatchCQB",
			"MET_mandalorian_deathwatchSergeant",
			"MET_mandalorian_deathwatchCaptain",

			"MET_mandalorianBackpack_journeyman",
			"MET_mandalorianBackpack_heavy",
			"MET_mandalorianBackpack_medic",
			"MET_mandalorianBackpack_cqb",
			"MET_mandalorianBackpack_sniper",
			"MET_mandalorianBackpack_at",
			"MET_mandalorianBackpack_aa",
			"MET_mandalorianBackpack_command",
		};
		weapons[]={};
		requiredAddons[]=
		{
			"A3_characters_F",
            "ls_characters_mandalorian",
			"MET_Deathwatch_Gear",
			"metal_death_weap"
		};
		skipWhenMissingDependencies=1;
	};
};
class CfgFactionClasses
{
	class DEATH_Units
	{
		displayName="[16th] DeathWatch";
		priority=1;
		side=0;
	};
};
class CfgEditorCategories
{
	class BHA_Assets
	{
		displayName = "Barysaw Holdings Authority";
		priority=1;
		side=2;
	};
};
class CfgEditorSubcategories
{
	class DEATH_Soldiers
	{
		displayName="Men (Deathwatch)";
	};
};
class ItemInfo;
class CfgVehicles
{
    class ls_backpack_base;
	class MET_mandalorianBackpack_journeyman: ls_backpack_base
	{
		scope=2;
		scopeArsenal=2;
		author="Legion Studios";
		displayName="[MET] Journeyman's Jetpack";
		model="\ls\core\addons\characters_mandalorian\backpacks\journeymanJet\ls_backpack_mandalorian_journeyman.p3d";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\ls\core\addons\characters_mandalorian\backpacks\journeymanJet\data\camo1_co.paa"
		};
		maximumLoad=300;
		tf_dialog="JLTS_clone_lr_programmer_radio_dialog";
		tf_dialogUpdate="call TFAR_fnc_updateLRDialogToChannel;";
		tf_encryptionCode="tf_east_radio_code";
		tf_hasLRradio=0;
		tf_range=10000;
		tf_subtype="digital_lr";
		sc_jumppack=1;
		sc_particles[]=
		{
			{0.15,-0.175,-0.2},
			{-0.15,-0.175,-0.2}
		};
	};
	class MET_mandalorianBackpack_Heavy: MET_mandalorianBackpack_journeyman
	{
		author="Legion Studios";
		displayName="[MET] Heavy's Jetpack";
		class TransportMagazines
		{
			class _xx_MET_blaster_battery_mand
			{
				count=5;
				name="MET_blaster_battery_mand";
			};
			class _xx_MANDO_HE_Grenade
			{
				count=5;
				name="MANDO_HE_Grenade";
			};
		};
	};
	class MET_mandalorianBackpack_Medic: MET_mandalorianBackpack_journeyman
	{
		author="Legion Studios";
		displayName="[MET] Medics's Jetpack";
		class TransportItems
		{
			class _xx_LFP_item_bacta_bandage
			{
				count=80;
				name="ACE_elasticBandage";
			};
			class _xx_Medikit
			{
				count=3;
				name="Medikit";
			};
		};
	};
	class MET_mandalorianBackpack_CQB: MET_mandalorianBackpack_journeyman
	{
		author="Legion Studios";
		displayName="[MET] CQB's Jetpack";
		class TransportMagazines
		{
			class _xx_MET_yellow_pellet_mag
			{
				count=10;
				name="MET_yellow_pellet_mag";
			};
			class _xx_MET_yellow_pellet_mag_bird
			{
				count=5;
				name="MET_yellow_pellet_mag_bird";
			};
		};
	};
	class MET_mandalorianBackpack_Sniper: MET_mandalorianBackpack_journeyman
	{
		author="Legion Studios";
		displayName="[MET] Sniper's Jetpack";
		class TransportMagazines
		{
			class _xx_MET_blaster_battery_mand
			{
				count=20;
				name="MET_773_mag";
			};
		};
	};
	class MET_mandalorianBackpack_AT: MET_mandalorianBackpack_journeyman
	{
		author="Legion Studios";
		displayName="[MET] AT's Jetpack";
		class TransportMagazines
		{
			class _xx_MET_MAND_AT_Single
			{
				count=3;
				name="MET_MAND_AT_Single";
			};
			class _xx_MET_MAND_AA_SINGLE
			{
				count=2;
				name="MET_MAND_AA_SINGLE";
			};
			class _xx_MET_MAND_AP_SINGLE
			{
				count=1;
				name="MET_MAND_AP_SINGLE";
			};
		};
	};
	class MET_mandalorianBackpack_AA: MET_mandalorianBackpack_journeyman
	{
		author="Legion Studios";
		displayName="[MET] AA's Jetpack";
		class TransportMagazines
		{
			class _xx_MET_MAND_AT_Single
			{
				count=2;
				name="MET_MAND_AT_Single";
			};
			class _xx_MET_MAND_AA_SINGLE
			{
				count=3;
				name="MET_MAND_AA_SINGLE";
			};
		};
	};
	class MET_mandalorianBackpack_Command: MET_mandalorianBackpack_journeyman
	{
		author="Legion Studios";
		displayName="[MET] Command's Jetpack";
		class TransportMagazines
		{
			class _xx_MET_yellow_pellet_mag
			{
				count=10;
				name="MET_yellow_pellet_mag";
			};
			class _xx_MET_yellow_pellet_mag_bird
			{
				count=5;
				name="MET_yellow_pellet_mag_bird";
			};
			class _xx_MET_Weapons_Mags_Ctype
			{
				count=2;
				name="MET_Weapons_Mags_Ctype";
			};
			class _xx_MET_Weapons_Mags_Thermal_Imploder
			{
				count=3;
				name="MET_Weapons_Mags_Thermal_Imploder";
			};
		};
	};
	class ls_mandalorian_traditionalWarrior;
	class MET_mandalorian_deathwatchWarrior: ls_mandalorian_traditionalWarrior
	{
		author="Legion Studios";
		side=0;
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_journeyman";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchWarrior.jpg";
		weapons[]=
		{
			"met_weapon_westar35c",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"met_weapon_westar35c",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_deathwatchSupportGunner;
	class MET_mandalorian_deathwatchHeavy: ls_mandalorian_deathwatchSupportGunner
	{
		author="Legion Studios";
		side=0;
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_Heavy";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchHeavy.jpg";
		weapons[]=
		{
			"MET_MANDALORIAN_Z6",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MET_MANDALORIAN_Z6",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MANDO_HE_Grenade",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MET_blaster_battery_mand",
			"MANDO_HE_Grenade",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_traditionalRTO;
	class MET_mandalorian_deathwatchRTO: ls_mandalorian_traditionalRTO
	{
		author="Legion Studios";
		side=0;
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_journeyman";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchRTO.jpg";
		weapons[]=
		{
			"met_weapon_westar35c",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"met_weapon_westar35c",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_traditionalMedic;
	class MET_mandalorian_deathwatchMedic: ls_mandalorian_traditionalMedic
	{
		author="Legion Studios";
		side=0;
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_Medic";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchMedic.jpg";
		weapons[]=
		{
			"met_weapon_westar35c",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"met_weapon_westar35c",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_traditionalMarksman;
	class MET_mandalorian_deathwatchMarksman: ls_mandalorian_traditionalMarksman
	{
		author="Legion Studios";
		side=0;
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_Sniper";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchMarksman.jpg";
		weapons[]=
		{
			"MET_weapon_firepuncher",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MET_weapon_firepuncher",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_773_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_traditionalAT;
	class MET_mandalorian_deathwatchAT: ls_mandalorian_traditionalAT
	{
		author="Legion Studios";
		side=0;
		displayName="Rocket Specialist (AT)";
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_AT";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchAT.jpg";
		weapons[]=
		{
			"met_weapon_westar35c",
			"MET_RPS6_SMRT",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"met_weapon_westar35c",
			"MET_RPS6_SMRT",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_MAND_AT_Single",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_MAND_AT_Single",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_traditionalHeavyAA;
	class MET_mandalorian_deathwatchHeavyAA: ls_mandalorian_traditionalHeavyAA
	{
		author="Legion Studios";
		side=0;
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_AA";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchHeavyAT.jpg";
		weapons[]=
		{
			"met_weapon_westar35c",
			"MET_RPS6_SMRT",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"met_weapon_westar35c",
			"MET_RPS6_SMRT",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_MAND_AA_Single",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_Westar35C_mag",
			"MET_MAND_AA_Single",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_traditionalDemo;
	class MET_mandalorian_deathwatchCQB: ls_mandalorian_traditionalDemo
	{
		author="Legion Studios";
		side=0;
		displayName="CQC";
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_CQB";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchDemo.jpg";
		weapons[]=
		{
			"MET_weapon_westar35s",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MET_weapon_westar35s",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag_bird",
			"MET_yellow_pellet_mag_bird",
			"MET_yellow_pellet_mag_bird",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchGrunt",
			"MET_mandalorianVest_deathwatchGrunt",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_traditionalSergeant;
	class MET_mandalorian_deathwatchSergeant: ls_mandalorian_traditionalSergeant
	{
		author="Legion Studios";
		side=0;
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_Command";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchSergeant.jpg";
		weapons[]=
		{
			"MET_weapon_westar35s",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MET_weapon_westar35s",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag_bird",
			"MET_yellow_pellet_mag_bird",
			"MET_yellow_pellet_mag_bird",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchSergeant",
			"MET_mandalorianVest_deathwatchSergeant",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder5",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchSergeant",
			"MET_mandalorianVest_deathwatchSergeant",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder5",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
	class ls_mandalorian_traditionalCaptain;
	class MET_mandalorian_deathwatchCaptain: ls_mandalorian_traditionalCaptain
	{
		author="Legion Studios";
		side=0;
		editorSubcategory="DEATH_Soldiers";
		faction="DEATH_Units";
		uniformClass="MET_mandalorianUniform";
		backpack="MET_mandalorianBackpack_Command";
		editorPreview="\ls\core\addons\characters_mandalorian\data\ui\editorPreviews\ls_mandalorian_deathwatchCaptain.jpg";
		weapons[]=
		{
			"MET_weapon_westar35s",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"MET_weapon_westar35s",
			"MET_weapon_westar35sa",
			"Throw",
			"Put"
		};
		magazines[]=
		{
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag_bird",
			"MET_yellow_pellet_mag_bird",
			"MET_yellow_pellet_mag_bird",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		respawnMagazines[]=
		{
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_Westar35S_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_yellow_pellet_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Westar35SA_mag",
			"MET_Smoke_White",
			"MET_Smoke_White",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Imploder",
			"MET_Weapons_Mags_Thermal_Detonator",
			"MET_Weapons_Mags_Thermal_Detonator",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_elasticBandage",
			"ACE_morphine",
			"ACE_morphine",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_tourniquet",
			"ACE_splint",
			"ACE_splint",
			"LFP_sonar_device"
		};
		linkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchCaptain",
			"MET_mandalorianVest_deathwatchCaptain",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder5",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
		respawnLinkedItems[]=
		{
			"MET_mandalorianHelmet_deathwatchCaptain",
			"MET_mandalorianVest_deathwatchCaptain",
			"ItemMap",
			"ItemCompass",
			"ItemGPS",
			"ACE_Altimeter",
			"MET_mandalorian_rangefinder5",
			"ls_radios_hush98",
			"JLTS_CloneBinocular_black"
		};
	};
};